public network acess changed
intel/terraform-intel-azure-mssql pull request #6
Opened 2023-01-30 22:34 UTC by shreejam21

- changed the variable to false
- and for the examples with firewall and vnet rule to it allows IP ranges provides by the users
- updated the readme to reflect the change

2023-01-31 17:37 UTC, kalenarndt requested changes
Changes look good. Just small formatting changes in the examples. 

I would also add an issue to swap that `count` for the firewall rules to be a `for_each` since it's predictable

2023-01-31 17:37 UTC, kalenarndt commented on examples/intel-optimized-mssql-server-firewall-rules/main.tf
>      sql_public_access = "allow"
Map formatting is a bit off for the `tags` input and it needs a `terraform fmt`

2023-01-31 17:37 UTC, kalenarndt commented on examples/intel-optimized-mssql-server-virtual-network-rule/main.tf
>    }
Map formatting is a bit off for the `tags` input and it needs a `terraform fmt`

2023-01-31 17:37 UTC, kalenarndt commented on examples/intel-optimized-mssql-server/main.tf
>  }
Map formatting is a bit off for the `tags` input and it needs a `terraform fmt`

2023-01-31 20:00 UTC, shreejam21 commented
Added the for_each for firwall_rules
Tested and Formatted
Updated README,md

Can you take a look @kalenarndt

2023-02-01 17:28 UTC, kalenarndt approved these changes
Formatting looks good along with the logic changes from `count` to `for_each`

2023-02-08 14:27 UTC, lucasmelogithub approved these changes
LGMT

2023-02-08 14:28 UTC, lucasmelogithub commented
@shreejam21 Can you please validate all examples ran successfully?

2023-02-08 17:34 UTC, merged